# Generated by Django 2.2.11 on 2020-04-06 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20200405_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, help_text='Content of the note')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When the note was created.')),
                ('important', models.BooleanField(default=False, help_text='Mark as important for pinning to top of notes')),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Anchor')),
                ('entity_owner', models.OneToOneField(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.ForeignKey(help_text='Participant who created the note.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
