# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, help_text='When the note was updated'),
        ),
    ]
