# Generated by Django 2.2.11 on 2020-04-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='anchor',
        ),
    ]
