# Generated by Django 3.0.3 on 2020-02-22 02:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name for the license.')),
                ('terms', models.TextField(blank=True, help_text='Content of the terms.')),
                ('upload', models.FileField(blank=True, null=True, upload_to='license/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Content License',
                'verbose_name_plural': 'Content Licenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('fields_used', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Fields used by this template.', size=None)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When template was created.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name identifying the project.', max_length=75)),
                ('project_description', models.TextField(blank=True, help_text='Short description of a project.')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name by which the story is identified.', max_length=250)),
                ('story_description', models.TextField(blank=True, help_text='Short description of a story.')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial.Project')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.BooleanField(default=True, help_text='Was this item originally created by a user from this organization?')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Day item was created.')),
                ('name', models.TextField(help_text='Internal name for item.')),
                ('headline', models.TextField(help_text='Headline of the item')),
                ('description', models.TextField(blank=True, help_text='Description of the item.')),
                ('content', models.TextField(blank=True, help_text='Content of the item.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pitch', 'Pitch'), ('In Progress', 'In Progress'), ('Edit', 'Edit'), ('Revision', 'Revision'), ('Needs Review', 'Needs Review'), ('Ready', 'Ready')], help_text='Item status choice.', max_length=25)),
                ('due_edit', models.DateTimeField(blank=True, help_text='Due for edit.', null=True)),
                ('run_date', models.DateTimeField(blank=True, help_text='Planned run date.', null=True)),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of keywords for search.', size=None)),
                ('update_note', models.TextField(blank=True, help_text='Text commenting regarding any updates or corrections made to the item.')),
                ('excerpt', models.TextField(blank=True, help_text='Excerpt from the item.')),
                ('dateline', models.CharField(blank=True, help_text='Where and when the item was created.', max_length=150)),
                ('share_note', models.TextField(blank=True, help_text='Information for organizations making a copy of the item.')),
                ('topic_code', models.CharField(blank=True, help_text='Unique code as needed to designate topic or coverage.', max_length=75)),
                ('internal_code', models.CharField(blank=True, help_text='Unique code as needed for ingest sytems or internal use. Use as needed.', max_length=75)),
                ('length', models.CharField(blank=True, help_text='Length of item for audio or video.', max_length=75)),
                ('wordcount', models.CharField(blank=True, help_text='Wordcount for text-based items.', max_length=75)),
                ('related_links', models.TextField(blank=True, help_text='Relevant links that can be included with the item.')),
                ('github_link', models.URLField(blank=True, help_text='Link to code for any custom feature.', max_length=300)),
                ('sources', models.TextField(blank=True, help_text='List of sources in the item.')),
                ('edit_note', models.TextField(blank=True, help_text='Information regarding allowable extent of editing and suggestions for specific kinds of edits.')),
                ('pronounciations', models.TextField(blank=True, help_text='Information about pronouncing names or potentially difficult words.')),
                ('sponsors', models.TextField(blank=True, help_text='Sponsors or underwriters if need to indicate any.')),
                ('pull_quotes', models.TextField(blank=True, help_text='List of quotes and attributions to be used as pull quotes.')),
                ('embeds', models.TextField(blank=True, help_text='The necessary information to embed something like a Tweet, FB post, map or video.')),
                ('sidebar_content', models.TextField(blank=True, help_text='Content separate from body text meant for sidebar or inset presentation.')),
                ('series_title', models.TextField(blank=True, help_text='Title of the video series.')),
                ('episode_number', models.CharField(blank=True, help_text='If the video is part of a series, the episode number.', max_length=75)),
                ('usage_rights', models.TextField(blank=True, help_text='Information regarding the usage of the video if shared.')),
                ('tape_datetime', models.DateTimeField(blank=True, help_text='Tape date.', null=True)),
                ('locations', models.TextField(blank=True, help_text='Shoot locations.')),
                ('custom_one', models.TextField(blank=True, help_text='User-defined field.')),
                ('custom_two', models.TextField(blank=True, help_text='User-defined field.')),
                ('custom_three', models.TextField(blank=True, help_text='User-defined field.')),
                ('custom_four', models.TextField(blank=True, help_text='User-defined field.')),
                ('custom_five', models.TextField(blank=True, help_text='User-defined field.')),
                ('content_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemlicense', to='editorial.ContentLicense')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.Story')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editorial.ItemTemplate')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
