# Generated by Django 3.0.3 on 2020-02-22 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='story',
        ),
        migrations.AlterField(
            model_name='item',
            name='content_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itemlicense', to='editorial.ContentLicense'),
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
