# Generated by Django 2.2.11 on 2020-04-06 02:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_auto_20200405_1926'),
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name identifying the project.', max_length=75)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sensitive', models.BooleanField(default=False, help_text='Is a project sensitive, for limited viewing?')),
                ('collaborate', models.BooleanField(default=False, help_text='The project is being collaborated on with partners.')),
                ('archived', models.BooleanField(default=False, help_text='Is the content no longer active and needed?')),
                ('website', models.URLField(blank=True, help_text='Project website if applicable.', max_length=250)),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
                ('collaborate_with', models.ManyToManyField(blank=True, help_text='Partner profiles selected to have collaborative access.', related_name='collaboration_partners', to='base.Partner')),
                ('entity_owner', models.OneToOneField(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.OneToOneField(help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('team', models.ManyToManyField(blank=True, help_text='Contributing participant.', related_name='team_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
