# Generated by Django 2.2.11 on 2020-04-06 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200405_1926'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='collaborate_with',
            field=models.ManyToManyField(blank=True, help_text='Partner profiles selected to have collaborative access.', related_name='roject_collaboration_partners', to='base.Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='Contributing participant.', related_name='project_team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name by which the story is identified.', max_length=250)),
                ('original', models.BooleanField(default=True, help_text='If original to participant/entity, true. If picked up, false.')),
                ('embargo', models.BooleanField(default=False, help_text='Is a story embargoed?')),
                ('embargo_datetime', models.DateTimeField(blank=True, help_text='When is the story no longer under embargo.', null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When was the story created.')),
                ('sensitive', models.BooleanField(default=False, help_text='Is a story sensitive and viewing it limited only to the team working on it?')),
                ('share', models.BooleanField(default=False, help_text='The story is being shared with partners.')),
                ('share_date', models.DateTimeField(blank=True, help_text='Estimated date the story will be available', null=True)),
                ('ready_to_share', models.BooleanField(default=False, help_text='The story is finished and ready to be picked up.')),
                ('collaborate', models.BooleanField(default=False, help_text='The story is being collaborated on with partners.')),
                ('archived', models.BooleanField(default=False, help_text='Is the content no longer active and needed?')),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
                ('collaborate_with', models.ManyToManyField(blank=True, help_text='Partner profiles selected to have collaborative access.', related_name='story_collaboration_partners', to='base.Partner')),
                ('entity_owner', models.OneToOneField(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.OneToOneField(help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Project')),
                ('share_with', models.ManyToManyField(blank=True, help_text='Partner profiles selected to have access to shared content.', related_name='share_partners', to='base.Partner')),
                ('team', models.ManyToManyField(blank=True, help_text='Contributing participant.', related_name='story_team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
