# Generated by Django 3.0.3 on 2020-02-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_auto_20200221_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name by which the story is identified.', max_length=250)),
                ('story_description', models.TextField(blank=True, help_text='Short description of a story.')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='editorial.Project')),
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'ordering': ['name'],
            },
        ),
    ]
