# Generated by Django 2.2.11 on 2020-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_auto_20200428_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, help_text='Short description of a project.'),
        ),
    ]
