# Generated by Django 2.2.11 on 2020-04-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_project_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desc',
            new_name='sketch',
        ),
        migrations.AddField(
            model_name='story',
            name='sketch',
            field=models.TextField(blank=True, help_text='Short description of the story.'),
        ),
    ]
