# Generated by Django 3.0.3 on 2020-02-22 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0003_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Story'),
        ),
    ]
