# Generated by Django 3.0.3 on 2020-02-22 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_item_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='editorial.ItemTemplate'),
        ),
    ]
