# Generated by Django 2.2.11 on 2020-04-29 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0004_auto_20200428_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='entity_owner',
            field=models.OneToOneField(blank=True, help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner'),
        ),
        migrations.AlterField(
            model_name='story',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Project'),
        ),
    ]
