# Generated by Django 3.0.3 on 2020-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0005_auto_20200428_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='sketch',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sketch',
        ),
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, help_text='Short description of a story.'),
        ),
    ]
