# Generated by Django 3.0.3 on 2020-05-22 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_auto_20200517_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='content_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.ContentLicense'),
        ),
    ]
