# Generated by Django 2.2.11 on 2020-04-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_audioasset_documentasset_imageasset_simpleaudio_simpledocument_simpleimage_simplevideo_videoasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='audio_assets',
            field=models.ManyToManyField(blank=True, to='editorial.AudioAsset'),
        ),
        migrations.AddField(
            model_name='item',
            name='content_license',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.ContentLicense'),
        ),
        migrations.AddField(
            model_name='item',
            name='document_assets',
            field=models.ManyToManyField(blank=True, to='editorial.DocumentAsset'),
        ),
        migrations.AddField(
            model_name='item',
            name='image_assets',
            field=models.ManyToManyField(blank=True, to='editorial.ImageAsset'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='editorial.Tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='video_assets',
            field=models.ManyToManyField(blank=True, to='editorial.VideoAsset'),
        ),
    ]
