# Generated by Django 3.0.3 on 2020-06-11 00:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20200406_1650'),
        ('timeline', '0001_initial'),
        ('entity', '0004_auto_20200502_2133'),
        ('task', '0002_auto_20200501_2038'),
        ('freelance', '0001_initial'),
        ('editorial', '0007_auto_20200521_2048'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleImage',
            new_name='InternalImage',
        ),
    ]
