# Generated by Django 2.2.11 on 2020-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_anchor'),
        ('editorial', '0007_auto_20200406_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
        migrations.AddField(
            model_name='project',
            name='simple_audio_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleAudio'),
        ),
        migrations.AddField(
            model_name='project',
            name='simple_document_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleDocument'),
        ),
        migrations.AddField(
            model_name='project',
            name='simple_image_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleImage'),
        ),
        migrations.AddField(
            model_name='project',
            name='simple_video_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleVideo'),
        ),
        migrations.AddField(
            model_name='story',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
        migrations.AddField(
            model_name='story',
            name='simple_audio_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleAudio'),
        ),
        migrations.AddField(
            model_name='story',
            name='simple_document_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleDocument'),
        ),
        migrations.AddField(
            model_name='story',
            name='simple_image_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleImage'),
        ),
        migrations.AddField(
            model_name='story',
            name='simple_video_assets',
            field=models.ManyToManyField(blank=True, to='editorial.SimpleVideo'),
        ),
    ]
