# Generated by Django 3.0.3 on 2020-06-11 00:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20200501_2038'),
        ('timeline', '0001_initial'),
        ('base', '0002_auto_20200406_1650'),
        ('entity', '0004_auto_20200502_2133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelance', '0002_pitch_tags'),
        ('editorial', '0008_auto_20200610_1745'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleDocument',
            new_name='InternalDocument',
        ),
    ]
