# Generated by Django 3.0.3 on 2020-06-11 00:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20200502_2133'),
        ('base', '0002_auto_20200406_1650'),
        ('task', '0002_auto_20200501_2038'),
        ('timeline', '0001_initial'),
        ('freelance', '0002_pitch_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editorial', '0009_auto_20200610_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleAudio',
            new_name='InternalAudio',
        ),
    ]
