# Generated by Django 3.0.3 on 2020-06-11 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0011_auto_20200610_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='simple_audio_assets',
            new_name='internal_audio_assets',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='simple_document_assets',
            new_name='internal_document_assets',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='simple_image_assets',
            new_name='internal_image_assets',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='simple_video_assets',
            new_name='internal_video_assets',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='simple_audio_assets',
            new_name='internal_audio_assets',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='simple_document_assets',
            new_name='internal_document_assets',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='simple_image_assets',
            new_name='internal_image_assets',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='simple_video_assets',
            new_name='internal_video_assets',
        ),
    ]
