# Generated by Django 3.0.3 on 2020-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0012_auto_20200611_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageasset',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='internalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='internalvideo',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='videoasset',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
