# Generated by Django 3.0.3 on 2020-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0007_auto_20201126_1312'),
        ('task', '0004_auto_20201126_1312'),
        ('freelance', '0009_auto_20201126_1312'),
        ('timeline', '0003_auto_20201126_1312'),
        ('pickup', '0003_auto_20201126_1312'),
        ('editorial', '0013_auto_20200611_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentasset',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='documentasset',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='documentasset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='internalaudio',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='internalaudio',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='internaldocument',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='internaldocument',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='internalimage',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='internalimage',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='internalvideo',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='internalvideo',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='videoasset',
            name='entity_owner',
        ),
        migrations.RemoveField(
            model_name='videoasset',
            name='participant_owner',
        ),
        migrations.RemoveField(
            model_name='videoasset',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='item',
            name='audio_assets',
        ),
        migrations.RemoveField(
            model_name='item',
            name='document_assets',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_assets',
        ),
        migrations.RemoveField(
            model_name='item',
            name='video_assets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internal_video_assets',
        ),
        migrations.RemoveField(
            model_name='story',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='story',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='story',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='story',
            name='internal_video_assets',
        ),
        migrations.DeleteModel(
            name='AudioAsset',
        ),
        migrations.DeleteModel(
            name='DocumentAsset',
        ),
        migrations.DeleteModel(
            name='ImageAsset',
        ),
        migrations.DeleteModel(
            name='InternalAudio',
        ),
        migrations.DeleteModel(
            name='InternalDocument',
        ),
        migrations.DeleteModel(
            name='InternalImage',
        ),
        migrations.DeleteModel(
            name='InternalVideo',
        ),
        migrations.DeleteModel(
            name='VideoAsset',
        ),
    ]
