# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0017_auto_20201201_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='item',
            name='update_note',
        ),
        migrations.RemoveField(
            model_name='project',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='project',
            name='website',
        ),
        migrations.RemoveField(
            model_name='story',
            name='desc',
        ),
    ]
