# Generated by Django 3.0.3 on 2020-12-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0018_auto_20201204_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(blank=True, help_text='Short description of project.'),
        ),
        migrations.AddField(
            model_name='story',
            name='desc',
            field=models.TextField(blank=True, help_text='Short description of story.'),
        ),
    ]
