# Generated by Django 2.2.11 on 2020-04-06 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0006_audioasset_documentasset_imageasset_simpleaudio_simpledocument_simpleimage_simplevideo_videoasset'),
        ('base', '0004_auto_20200405_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPickupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_entity_owner_name', models.CharField(help_text='Name of original entity.', max_length=300)),
                ('original_story_name', models.CharField(help_text='Name of original story.', max_length=300)),
                ('partner_name', models.CharField(help_text='Name of partner.', max_length=300)),
                ('pickup_date', models.DateTimeField(auto_now_add=True, help_text='Datetime when pickup was made.')),
                ('original_entity_owner', models.OneToOneField(help_text='Entity that originally made the story available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('original_story', models.ForeignKey(help_text='ID of original instance of the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_story_detail', to='editorial.Story')),
                ('partner', models.OneToOneField(help_text='Partner picking up the story.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_pickup_partner', to='base.Partner')),
                ('partner_story', models.ForeignKey(help_text='ID of the new instance of the story saved by the pickup partner.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_pickup', to='editorial.Story')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPickupDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_entity_owner_name', models.CharField(help_text='Name of original entity.', max_length=300)),
                ('original_item_name', models.CharField(help_text='Name of original item.', max_length=300)),
                ('partner_name', models.CharField(help_text='Name of partner.', max_length=300)),
                ('pickup_date', models.DateTimeField(auto_now_add=True, help_text='Datetime when pickup was made.')),
                ('original_entity_owner', models.OneToOneField(help_text='Entity that originally made the item available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('original_item', models.ForeignKey(help_text='ID of original instance of the item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_item_detail', to='editorial.Item')),
                ('partner', models.OneToOneField(help_text='Partner picking up the item.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_pickup_partner', to='base.Partner')),
                ('partner_item', models.ForeignKey(help_text='The new version of the item saved by the partner organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_pickup', to='editorial.Item')),
            ],
        ),
    ]
