# Generated by Django 3.0.3 on 2020-06-21 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storypickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally made the story available.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storypickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of origin participant.', max_length=300),
        ),
        migrations.AlterField(
            model_name='storypickupdetail',
            name='original_entity_owner_name',
            field=models.CharField(blank=True, help_text='Name of original entity.', max_length=300),
        ),
    ]
