# Generated by Django 3.0.3 on 2020-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_auto_20200620_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiopickupdetail',
            name='original_audioasset',
        ),
        migrations.RemoveField(
            model_name='audiopickupdetail',
            name='partner_audioasset',
        ),
        migrations.RemoveField(
            model_name='documentpickupdetail',
            name='original_documentasset',
        ),
        migrations.RemoveField(
            model_name='documentpickupdetail',
            name='partner_documentasset',
        ),
        migrations.RemoveField(
            model_name='imagepickupdetail',
            name='original_imageasset',
        ),
        migrations.RemoveField(
            model_name='imagepickupdetail',
            name='partner_imageasset',
        ),
        migrations.RemoveField(
            model_name='videopickupdetail',
            name='original_videoasset',
        ),
        migrations.RemoveField(
            model_name='videopickupdetail',
            name='partner_videoasset',
        ),
    ]
