# Generated by Django 3.0.3 on 2020-11-27 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0016_auto_20201126_1835'),
        ('pickup', '0003_auto_20201126_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopickupdetail',
            name='original_audioasset',
            field=models.ForeignKey(help_text='Original instance of the audioasset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_audioasset_detail', to='editorial.AudioAsset'),
        ),
        migrations.AddField(
            model_name='audiopickupdetail',
            name='partner_audioasset',
            field=models.ForeignKey(help_text='The copied version of the audioasset saved by the partner organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audioasset_pickup', to='editorial.AudioAsset'),
        ),
        migrations.AddField(
            model_name='documentpickupdetail',
            name='original_documentasset',
            field=models.ForeignKey(help_text='Original instance of the documentasset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_documentasset_detail', to='editorial.DocumentAsset'),
        ),
        migrations.AddField(
            model_name='documentpickupdetail',
            name='partner_documentasset',
            field=models.ForeignKey(help_text='The copied version of the documentasset saved by the partner organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentasset_pickup', to='editorial.DocumentAsset'),
        ),
        migrations.AddField(
            model_name='imagepickupdetail',
            name='original_imageasset',
            field=models.ForeignKey(help_text='Original instance of the imageasset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_imageasset_detail', to='editorial.ImageAsset'),
        ),
        migrations.AddField(
            model_name='imagepickupdetail',
            name='partner_imageasset',
            field=models.ForeignKey(help_text='The copied version of the imageasset saved by the partner organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imageasset_pickup', to='editorial.ImageAsset'),
        ),
        migrations.AddField(
            model_name='videopickupdetail',
            name='original_videoasset',
            field=models.ForeignKey(help_text='Original instance of the videoasset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_videoasset_detail', to='editorial.VideoAsset'),
        ),
        migrations.AddField(
            model_name='videopickupdetail',
            name='partner_videoasset',
            field=models.ForeignKey(help_text='The copied version of the videoasset saved by the partner organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videoasset_pickup', to='editorial.VideoAsset'),
        ),
    ]
