# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0004_auto_20201126_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiopickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally created/owned this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audiopickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='documentpickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally created/owned this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='imagepickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally created/owned this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagepickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='itempickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally created/owned the item.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
        migrations.AddField(
            model_name='videopickupdetail',
            name='original_participant_owner',
            field=models.OneToOneField(help_text='Participant that originally created/owned this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='videopickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
        migrations.AlterField(
            model_name='storypickupdetail',
            name='original_participant_owner_name',
            field=models.CharField(blank=True, help_text='Name of original participant owner.', max_length=300),
        ),
    ]
