# Generated by Django 3.0.3 on 2020-04-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffjournalist_type', models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Staff', 'Staff'), ('Other', 'Other')], help_text='Type of staff journalist.', max_length=25)),
                ('newsorganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.NewsOrganization')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Journalist',
                'verbose_name_plural': 'Staff Journalists',
            },
        ),
    ]
