# Generated by Django 2.2.11 on 2020-04-29 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnaffiliatedStaffJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsorganization', models.CharField(blank=True, help_text='Name of the off platform news organization.', max_length=350)),
                ('newsorganization_website', models.URLField(blank=True, help_text='Link to news organization website.', max_length=500, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staffjournalist', models.ForeignKey(blank=True, help_text='Account of Affiliated Staff Journalist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffJournalist')),
            ],
            options={
                'verbose_name_plural': 'Unaffiliated Staff Journalists',
                'verbose_name': 'Unaffiliated Staff Journalist',
            },
        ),
    ]
