# Generated by Django 3.0.3 on 2020-11-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_unaffiliatedstaffjournalist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unaffiliatedstaffjournalist',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='unaffiliatedstaffjournalist',
            name='staffjournalist',
        ),
        migrations.DeleteModel(
            name='StaffJournalist',
        ),
        migrations.DeleteModel(
            name='UnaffiliatedStaffJournalist',
        ),
    ]
