# Generated by Django 2.2.11 on 2020-04-06 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, help_text='Is this freelance manager publicly listed?')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelance Manager',
                'verbose_name_plural': 'Freelance Managers',
            },
        ),
        migrations.CreateModel(
            name='FreelanceJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, help_text='PDF of contractor resume.', null=True, upload_to='resumes/%Y/%m/%d')),
                ('address', models.TextField(blank=True, help_text='Mailing address.')),
                ('availability', models.TextField(blank=True, help_text='Notes on when a contractor is available or not.')),
                ('current_location', models.TextField(blank=True, help_text="Freelancer's specific location.")),
                ('gear', models.TextField(blank=True, help_text='Gear that a contractor has access to and skills for.')),
                ('public', models.BooleanField(default=True, help_text='Is the contractor publicly listed?')),
                ('portfolio_link1', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('portfolio_link2', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('portfolio_link3', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelance Journalist',
                'verbose_name_plural': 'Freelance Journalists',
            },
        ),
    ]
