# Generated by Django 3.0.3 on 2020-06-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0008_auto_20200610_1745'),
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='tags',
            field=models.ManyToManyField(blank=True, to='editorial.Tag'),
        ),
    ]
