# Generated by Django 2.2.11 on 2020-04-06 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_auto_20200405_1926'),
        ('freelance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelanceInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(help_text='Text or numberic short identifier for Invoice.', max_length=300)),
                ('text', models.TextField(help_text='Details of the invoice.')),
                ('total_due', models.IntegerField(help_text='Total value of the invoice.')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Day assignment was created.')),
                ('submitted', models.BooleanField(default=False, help_text='Invoice has been submitted.')),
                ('submitted_date', models.DateTimeField(blank=True, help_text='Datetime invoice was submitted to talent editor.')),
                ('under_review', models.BooleanField(default=False, help_text='Invoice is under review by Freelance Manager/News Organization.')),
                ('paid', models.BooleanField(default=False, help_text='Payment has been remitted for this assignment.')),
                ('payment_submitted_date', models.DateTimeField(blank=True, help_text='Datetime payment was remitted or scheduled to remit to freelancer.')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceJournalist')),
                ('manager', models.ForeignKey(help_text='Manager responsible for this assignment.', on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceManager')),
                ('organization', models.ForeignKey(help_text='Organization that owns this assignment.', on_delete=django.db.models.deletion.CASCADE, to='entity.NewsOrganization')),
            ],
            options={
                'verbose_name': 'Freelance Invoice',
                'verbose_name_plural': 'Freelance Invoices',
            },
        ),
        migrations.CreateModel(
            name='OrganizationAffiliationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, help_text='Any notes for freelancer to remember about this affiliation.')),
                ('favorite', models.BooleanField(default=False, help_text='Is this news organization a favored contract?')),
                ('contacts', models.ManyToManyField(blank=True, help_text='News Organization Freelance Managers freelancer works with.', related_name='affilation_contact', to='freelance.FreelanceManager')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceJournalist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.NewsOrganization')),
            ],
            options={
                'verbose_name': 'News Organization Affiliation Record',
                'unique_together': {('organization', 'freelancer')},
                'verbose_name_plural': 'News Organization Affiliation Records',
            },
        ),
        migrations.CreateModel(
            name='FreelancerAffiliationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w9_on_file', models.BooleanField(default=False, help_text='Does the organization have a W9 on file.')),
                ('rates', models.TextField(blank=True, help_text='The rates the freelancer is paid by the org.')),
                ('strengths', models.TextField(blank=True, help_text='Internal notes on strengths of the freelancer.')),
                ('disclosures', models.TextField(blank=True, help_text='Disclosures regarind any potential noteworthy conflicts of interest.')),
                ('editor_notes', models.TextField(blank=True, help_text='Any notes for editors on things to know when working with this freelancer.')),
                ('vetted', models.BooleanField(default=False, help_text='Is this freelancer a trusted regular?')),
                ('status', models.BooleanField(default=True, help_text='Is this freelancer currently working for the organization?')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceJournalist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.NewsOrganization')),
            ],
            options={
                'verbose_name': 'Freelancer Affiliation Record',
                'unique_together': {('organization', 'freelancer')},
                'verbose_name_plural': 'Freelancer Affiliation Records',
            },
        ),
    ]
