# Generated by Django 3.0.3 on 2020-06-21 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200620_2012'),
        ('freelance', '0003_auto_20200611_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='anchor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor'),
        ),
        migrations.AddField(
            model_name='pitch',
            name='anchor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor'),
        ),
    ]
