# Generated by Django 2.2.11 on 2020-04-06 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_audioasset_documentasset_imageasset_simpleaudio_simpledocument_simpleimage_simplevideo_videoasset'),
        ('freelance', '0003_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Title of the pitch.')),
                ('text', models.TextField(help_text='Text of the pitch.')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Day pitch was created.')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pitched', 'Pitched'), ('Accepted', 'Accepted'), ('Complete', 'Complete')], help_text='Pitch status choice.', max_length=25)),
                ('exclusive', models.BooleanField(default=False, help_text='Is this pitch for an assignment exclusive to the recipient?')),
                ('call', models.ForeignKey(blank=True, help_text='Call if pitch is in response to a call.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelance.Call')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceJournalist')),
                ('recipient', models.ForeignKey(blank=True, help_text='Freelance Manager being pitched.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelance.FreelanceManager')),
                ('simple_audio_assets', models.ManyToManyField(blank=True, to='editorial.SimpleAudio')),
                ('simple_document_assets', models.ManyToManyField(blank=True, to='editorial.SimpleDocument')),
                ('simple_image_assets', models.ManyToManyField(blank=True, to='editorial.SimpleImage')),
                ('simple_video_assets', models.ManyToManyField(blank=True, to='editorial.SimpleVideo')),
            ],
            options={
                'verbose_name': 'Freelance Pitch',
                'verbose_name_plural': 'Freelance Pitches',
            },
        ),
    ]
