# Generated by Django 3.0.3 on 2020-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0004_auto_20200620_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancemanager',
            name='interest',
            field=models.TextField(blank=True, help_text='Description of stories interested in.'),
        ),
    ]
