# Generated by Django 2.2.11 on 2020-04-06 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0006_audioasset_documentasset_imageasset_simpleaudio_simpledocument_simpleimage_simplevideo_videoasset'),
        ('entity', '0003_auto_20200405_1926'),
        ('freelance', '0004_pitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the assignment.')),
                ('text', models.TextField(help_text='Details of the assignment.')),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Day assignment was created.')),
                ('complete', models.BooleanField(default=False, help_text='Is the assignment complete?')),
                ('rate', models.CharField(help_text='Rate at which the assignment is being completed.', max_length=100)),
                ('invoiced', models.BooleanField(default=False, help_text='An invoice has been submitted for this assignment.')),
                ('paid', models.BooleanField(default=False, help_text='Payment has been remitted for this assignment.')),
                ('call', models.ForeignKey(blank=True, help_text='If this assignment is related to a call, which one?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelance.Call')),
                ('editor', models.ForeignKey(help_text='Editor responsible for this assignment.', on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceManager')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freelance.FreelanceJournalist')),
                ('item', models.ForeignKey(blank=True, help_text='Which item is this assignment related to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Item')),
                ('organization', models.ForeignKey(help_text='Organization that owns this assignment.', on_delete=django.db.models.deletion.CASCADE, to='entity.NewsOrganization')),
                ('pitch', models.ForeignKey(blank=True, help_text='If this assignment is related to a pitch, which one?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='freelance.Pitch')),
                ('project', models.ForeignKey(blank=True, help_text='Which project is this assignment related to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Project')),
                ('simple_audio_assets', models.ManyToManyField(blank=True, to='editorial.SimpleAudio')),
                ('simple_document_assets', models.ManyToManyField(blank=True, to='editorial.SimpleDocument')),
                ('simple_image_assets', models.ManyToManyField(blank=True, to='editorial.SimpleImage')),
                ('simple_video_assets', models.ManyToManyField(blank=True, to='editorial.SimpleVideo')),
                ('story', models.ForeignKey(blank=True, help_text='Which story is this assignment related to?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='editorial.Story')),
            ],
            options={
                'verbose_name': 'Freelance Assignment',
                'verbose_name_plural': 'Freelance Assignments',
            },
        ),
    ]
