# Generated by Django 2.2.11 on 2020-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('freelance', '0005_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceraffiliationrecord',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
    ]
