# Generated by Django 3.0.3 on 2020-06-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0005_freelancemanager_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='total_due',
            field=models.DecimalField(decimal_places=2, help_text='Total value of the invoice.', max_digits=6),
        ),
    ]
