# Generated by Django 3.0.3 on 2020-11-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_freelancesubscription_freelancer'),
        ('freelance', '0006_auto_20200621_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancemanager',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='call',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='recipient',
        ),
        migrations.AlterField(
            model_name='freelanceinvoice',
            name='total_due',
            field=models.DecimalField(decimal_places=2, help_text='Total value of the invoice.', max_digits=8),
        ),
        migrations.AlterUniqueTogether(
            name='freelanceraffiliationrecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='organizationaffiliationrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='freelanceraffiliationrecord',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='organizationaffiliationrecord',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='organizationaffiliationrecord',
            name='freelancer',
        ),
        migrations.DeleteModel(
            name='FreelanceJournalist',
        ),
        migrations.DeleteModel(
            name='FreelanceManager',
        ),
    ]
