# Generated by Django 3.0.3 on 2020-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freelance', '0008_auto_20201125_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='internal_video_assets',
        ),
        migrations.RemoveField(
            model_name='call',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='call',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='call',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='call',
            name='internal_video_assets',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='freelanceinvoice',
            name='internal_video_assets',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='pitch',
            name='internal_video_assets',
        ),
    ]
