# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0010_auto_20201204_2010'),
        ('freelance', '0011_auto_20201201_1855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='internal_audio_assets',
            new_name='internal_audio',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='internal_document_assets',
            new_name='internal_documents',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='internal_image_assets',
            new_name='internal_images',
        ),
        migrations.RenameField(
            model_name='call',
            old_name='internal_video_assets',
            new_name='internal_videos',
        ),
        migrations.AlterField(
            model_name='call',
            name='organization',
            field=models.ForeignKey(help_text='NewsOrganization that is making this call.', on_delete=django.db.models.deletion.CASCADE, to='entity.NewsOrganization'),
        ),
        migrations.AlterField(
            model_name='call',
            name='timeframe',
            field=models.CharField(blank=True, help_text='The timeframe for response.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='urgent',
            field=models.BooleanField(default=False, help_text='The urgency of the call'),
        ),
        migrations.AlterField(
            model_name='freelanceraffiliationrecord',
            name='disclosures',
            field=models.TextField(blank=True, help_text='Disclosures regarding any potential noteworthy conflicts of interest.'),
        ),
    ]
