# Generated by Django 3.0.3 on 2020-12-02 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_auto_20200620_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Link to website.', max_length=500, null=True)),
                ('description', models.CharField(blank=True, help_text='Short description of web link.', max_length=500)),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
            ],
            options={
                'verbose_name': 'URL',
                'verbose_name_plural': 'URLs',
                'ordering': ['anchor_profile'],
            },
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, help_text='Link to profile.', max_length=500, null=True)),
                ('platform', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Reddit', 'Reddit'), ('TikTok', 'TikTok'), ('Tumblr', 'Tumblr'), ('YouTube', 'YouTube'), ('Vimeo', 'Vimeo'), ('Pinterest', 'Pinterest'), ('Twitch', 'Twitch')], help_text='Platform of profile.', max_length=25)),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
            ],
            options={
                'verbose_name': 'Platform Profile',
                'verbose_name_plural': 'Platform Profiles',
                'ordering': ['anchor_profile'],
            },
        ),
    ]
