# Generated by Django 3.0.3 on 2020-11-26 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0006_auto_20200611_0950'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffjournalist_type', models.CharField(choices=[('Admin', 'Admin'), ('Editor', 'Editor'), ('Staff', 'Staff'), ('Other', 'Other')], help_text='Type of staff journalist.', max_length=25)),
                ('newsorganization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity.NewsOrganization')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Journalist',
                'verbose_name_plural': 'Staff Journalists',
            },
        ),
        migrations.CreateModel(
            name='UnaffiliatedStaffJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsorganization', models.CharField(blank=True, help_text='Name of the off platform news organization.', max_length=350)),
                ('newsorganization_website', models.URLField(blank=True, help_text='Link to news organization website.', max_length=500, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('staffjournalist', models.ForeignKey(blank=True, help_text='Account of Affiliated Staff Journalist', null=True, on_delete=django.db.models.deletion.SET_NULL, to='participant.StaffJournalist')),
            ],
            options={
                'verbose_name': 'Unaffiliated Staff Journalist',
                'verbose_name_plural': 'Unaffiliated Staff Journalists',
            },
        ),
        migrations.CreateModel(
            name='FreelanceManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.BooleanField(default=False, help_text='Is this freelance manager publicly listed?')),
                ('interest', models.TextField(blank=True, help_text='Description of stories interested in.')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelance Manager',
                'verbose_name_plural': 'Freelance Managers',
            },
        ),
        migrations.CreateModel(
            name='FreelanceJournalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(blank=True, help_text='PDF of contractor resume.', null=True, upload_to='resumes/%Y/%m/%d')),
                ('address', models.TextField(blank=True, help_text='Mailing address.')),
                ('availability', models.TextField(blank=True, help_text='Notes on when a contractor is available or not.')),
                ('current_location', models.TextField(blank=True, help_text="Freelancer's specific location.")),
                ('gear', models.TextField(blank=True, help_text='Gear that a contractor has access to and skills for.')),
                ('public', models.BooleanField(default=True, help_text='Is the contractor publicly listed?')),
                ('portfolio_link1', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('portfolio_link2', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('portfolio_link3', models.URLField(blank=True, help_text='Link to portfolio item.', max_length=500, null=True)),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelance Journalist',
                'verbose_name_plural': 'Freelance Journalists',
            },
        ),
    ]
