# Generated by Django 3.0.3 on 2020-04-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('editorial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Name of the event.')),
                ('text', models.TextField(blank=True, help_text='Description of the event.')),
                ('event_type', models.CharField(choices=[('Hosting', 'Hosting'), ('Reporting', 'Reporting'), ('Administrative', 'Administrative'), ('Other', 'Other')], help_text='Kind of event.', max_length=50)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='Date and time event is created.')),
                ('event_date', models.DateTimeField(blank=True, help_text='Date and time of the event.')),
                ('venue', models.TextField(blank=True, help_text='The location of the event.')),
                ('anchor', models.OneToOneField(help_text='The anchor object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_anchor', to='base.Anchor')),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
                ('entity_owner', models.OneToOneField(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('notes', models.ManyToManyField(blank=True, to='note.Note')),
                ('participant_owner', models.OneToOneField(help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('simple_audio_assets', models.ManyToManyField(blank=True, to='editorial.SimpleAudio')),
                ('simple_document_assets', models.ManyToManyField(blank=True, to='editorial.SimpleDocument')),
                ('simple_image_assets', models.ManyToManyField(blank=True, to='editorial.SimpleImage')),
                ('simple_video_assets', models.ManyToManyField(blank=True, to='editorial.SimpleVideo')),
                ('team', models.ManyToManyField(blank=True, help_text='The participants assigned to an event.', related_name='event_team', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['name'],
            },
        ),
    ]
