# Generated by Django 3.0.3 on 2020-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_auto_20200611_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='event',
            name='internal_video_assets',
        ),
    ]
