# Generated by Django 3.0.3 on 2020-11-26 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancesubscription',
            name='freelancer',
        ),
    ]
