# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
        ('subscription', '0002_remove_freelancesubscription_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancesubscription',
            name='freelancer',
            field=models.ForeignKey(default=1, help_text='Freelancer associated with this subscription.', on_delete=django.db.models.deletion.CASCADE, to='participant.FreelanceJournalist'),
            preserve_default=False,
        ),
    ]
