# Generated by Django 3.0.3 on 2020-04-06 23:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.CharField(choices=[('NEWS ORGANIZATION', 'News Organization'), ('NEWS ORGANIZATION NETWORK', 'News Organization Network'), ('PROJECT', 'Project'), ('STORY', 'Story'), ('ITEM', 'Item'), ('TASK', 'Task'), ('EVENT', 'Event')], help_text='What kind of anchor it is.', max_length=250)),
                ('anchor_name', models.CharField(help_text='Name of the anchor.', max_length=250)),
                ('anchor_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Anchor Profile',
                'verbose_name_plural': 'Anchor Profiles',
            },
        ),
        migrations.CreateModel(
            name='EntityOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('NEWSORGANIZATION', 'News Organization'), ('NEWSORGANIZATIONNETWORK', 'News Organization Network')], help_text='What kind of entity it is.', max_length=250)),
                ('owner_name', models.CharField(help_text='Name of the entity', max_length=250)),
                ('owner_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Entity Owner Profile',
                'verbose_name_plural': 'Entity Owner Profiles',
            },
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('NEWSORGANIZATION', 'News Organization')], help_text='What kind of member it is.', max_length=250)),
                ('member_name', models.CharField(help_text='Name of the member.', max_length=250)),
                ('member_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('NEWS ORGANIZATION', 'News Organization'), ('NEWS ORGANIZATION NETWORK', 'News Organization Network')], help_text='What kind of partner it is.', max_length=250)),
                ('partner_name', models.CharField(help_text='Name of the partner.', max_length=250)),
                ('partner_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('display_name', models.CharField(blank=True, help_text='Shorter version of name used to identify participant to other participants.', max_length=100)),
                ('credit_name', models.CharField(blank=True, help_text='Full name of participant as listed as a public credit on content.', max_length=75)),
                ('name_pronunciation', models.TextField(blank=True, help_text='Instruction on the proper pronunciation of participant name.')),
                ('pronoun', models.CharField(blank=True, help_text='Participants preferred pronouns.', max_length=50)),
                ('title', models.CharField(blank=True, help_text='Professional title.', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('biography', models.TextField(blank=True, help_text='Short bio.')),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('expertise', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Array of participant skills and beats to filter/search by.', size=None)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['credit_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
