# Generated by Django 2.2.11 on 2020-04-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_type', models.CharField(choices=[('NEWS ORGANIZATION', 'News Organization'), ('NEWS ORGANIZATION NETWORK', 'News Organization Network'), ('PROJECT', 'Project'), ('STORY', 'Story'), ('ITEM', 'Item'), ('TASK', 'Task'), ('EVENT', 'Event')], help_text='What kind of anchor it is.', max_length=250)),
                ('anchor_name', models.CharField(help_text='Name of the anchor.', max_length=250)),
                ('anchor_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Anchor Profile',
                'verbose_name_plural': 'Anchor Profiles',
            },
        ),
        migrations.CreateModel(
            name='EntityOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type', models.CharField(choices=[('NEWSORGANIZATION', 'News Organization'), ('NEWSORGANIZATIONNETWORK', 'News Organization Network')], help_text='What kind of entity it is.', max_length=250)),
                ('owner_name', models.CharField(help_text='Name of the entity', max_length=250)),
                ('owner_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Entity Owner Profile',
                'verbose_name_plural': 'Entity Owner Profiles',
            },
        ),
        migrations.CreateModel(
            name='NetworkMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('NEWSORGANIZATION', 'News Organization')], help_text='What kind of entity it is.', max_length=250)),
                ('member_name', models.CharField(help_text='Name of the member.', max_length=250)),
                ('member_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Member Profile',
                'verbose_name_plural': 'Member Profiles',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_type', models.CharField(choices=[('PARTICIPANT', 'Participant'), ('NEWS ORGANIZATION', 'News Organization'), ('NEWS ORGANIZATION NETWORK', 'News Organization Network')], help_text='What kind of partner it is.', max_length=250)),
                ('partner_name', models.CharField(help_text='Name of the partner.', max_length=250)),
                ('partner_id', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
            },
        ),
    ]
