# Generated by Django 3.0.3 on 2020-04-06 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
        migrations.AddField(
            model_name='participant',
            name='partner_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Partner'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
