# Generated by Django 2.2.11 on 2020-04-06 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_anchor_entityowner_networkmember_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='anchor_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor'),
        ),
        migrations.AddField(
            model_name='participant',
            name='partner_profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Partner'),
        ),
    ]
