# Generated by Django 3.0.3 on 2020-06-12 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_participant_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='connections',
            field=models.ManyToManyField(blank=True, help_text='Participants that are connections.', related_name='_participant_connections_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
