# Generated by Django 2.2.11 on 2020-04-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200405_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmember',
            name='member_type',
            field=models.CharField(choices=[('NEWSORGANIZATION', 'News Organization')], help_text='What kind of member it is.', max_length=250),
        ),
    ]
