# Generated by Django 2.2.11 on 2020-04-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
        ('base', '0004_auto_20200405_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='notes',
            field=models.ManyToManyField(blank=True, to='note.Note'),
        ),
    ]
