# Generated by Django 3.0.3 on 2020-06-21 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_participant_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='anchor_type',
            field=models.CharField(choices=[('NEWS ORGANIZATION', 'News Organization'), ('NEWS ORGANIZATION NETWORK', 'News Organization Network'), ('PROJECT', 'Project'), ('STORY', 'Story'), ('ITEM', 'Item'), ('TASK', 'Task'), ('EVENT', 'Event'), ('PITCH', 'Pitch'), ('ASSIGNMENT', 'Assignment')], help_text='What kind of anchor it is.', max_length=250),
        ),
    ]
