# Generated by Django 3.0.3 on 2020-11-27 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0005_auto_20200620_2012'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Text for file name. Name it intuitively.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What is the asset. (If a photo or graphic, it should be the caption.)', max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When the asset was created.')),
                ('sensitive', models.BooleanField(default=False, help_text='Is the asset sensitive, or associated with sensitve content?')),
                ('video', models.FileField(blank=True, upload_to='videos')),
                ('thumbnail', models.FileField(blank=True, upload_to='videos')),
                ('link', models.URLField(blank=True, help_text='Link to video file hosted elsewhere.', max_length=400)),
                ('entity_owner', models.ForeignKey(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.ForeignKey(blank=True, help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Text for file name. Name it intuitively.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What is the asset. (If a photo or graphic, it should be the caption.)', max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When the asset was created.')),
                ('sensitive', models.BooleanField(default=False, help_text='Is the asset sensitive, or associated with sensitve content?')),
                ('image', models.ImageField(blank=True, upload_to='photos')),
                ('entity_owner', models.ForeignKey(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.ForeignKey(blank=True, help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Text for file name. Name it intuitively.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What is the asset. (If a photo or graphic, it should be the caption.)', max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When the asset was created.')),
                ('sensitive', models.BooleanField(default=False, help_text='Is the asset sensitive, or associated with sensitve content?')),
                ('document', models.FileField(blank=True, upload_to='documents')),
                ('entity_owner', models.ForeignKey(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.ForeignKey(blank=True, help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Text for file name. Name it intuitively.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What is the asset. (If a photo or graphic, it should be the caption.)', max_length=300)),
                ('creation_date', models.DateTimeField(auto_now_add=True, help_text='When the asset was created.')),
                ('sensitive', models.BooleanField(default=False, help_text='Is the asset sensitive, or associated with sensitve content?')),
                ('audio', models.FileField(blank=True, upload_to='audio')),
                ('link', models.URLField(blank=True, help_text='Link to audio file hosted elsewhere.', max_length=400)),
                ('entity_owner', models.ForeignKey(help_text='Entity that owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('participant_owner', models.ForeignKey(blank=True, help_text='Participant who created/owns this.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
