# Generated by Django 3.0.3 on 2020-12-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalasset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='internalvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='videos'),
        ),
    ]
