# Generated by Django 2.2.11 on 2020-04-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsorganization',
            name='business_structure',
            field=models.CharField(blank=True, choices=[('Nonprofit - 501c3', 'Nonprofit'), ('For profit', 'For profit'), ('B Corp', 'B Corporation'), ('Cooperative', 'Cooperative'), ('Direct Offering', 'Direct Offering'), ('Hybrid', 'Hybrid'), ('Employee Owned', 'Employee Owned'), ('Other', 'Other')], help_text='Business structure of the news organization.', max_length=50),
        ),
    ]
