# Generated by Django 2.2.11 on 2020-04-06 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200405_1815'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsOrganizationNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The identifying name of the network.', max_length=350)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('anchor_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Anchor')),
                ('entity_owner', models.ForeignKey(help_text='Entity that owns this network.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='network_owner', to='base.EntityOwner')),
                ('entity_owner_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.EntityOwner')),
                ('members', models.ManyToManyField(related_name='network_newsorganization', to='base.NetworkMember')),
                ('participant_owner', models.ForeignKey(help_text='Participant who owns this organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('partner_profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.Partner')),
            ],
            options={
                'verbose_name_plural': 'News Organization Networks',
                'verbose_name': 'News Organization Network',
                'ordering': ['name'],
            },
        ),
    ]
