# Generated by Django 3.0.3 on 2020-05-03 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entity', '0002_auto_20200406_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsorganizationnetwork',
            name='participant_owner',
            field=models.ForeignKey(blank=True, help_text='Participant who owns this network.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
