# Generated by Django 3.0.3 on 2020-06-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20200611_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsorganization',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='org_cover'),
        ),
        migrations.AddField(
            model_name='newsorganization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='news_organizations'),
        ),
        migrations.AddField(
            model_name='newsorganizationnetwork',
            name='logo',
            field=models.ImageField(blank=True, upload_to='networks'),
        ),
    ]
