# Generated by Django 3.0.3 on 2020-11-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20200611_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsorganization',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganization',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganization',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganization',
            name='internal_video_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganizationnetwork',
            name='internal_audio_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganizationnetwork',
            name='internal_document_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganizationnetwork',
            name='internal_image_assets',
        ),
        migrations.RemoveField(
            model_name='newsorganizationnetwork',
            name='internal_video_assets',
        ),
    ]
