# Generated by Django 3.0.3 on 2020-11-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internalasset', '0001_initial'),
        ('entity', '0007_auto_20201126_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsorganization',
            name='internal_audio_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalAudio'),
        ),
        migrations.AddField(
            model_name='newsorganization',
            name='internal_document_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalDocument'),
        ),
        migrations.AddField(
            model_name='newsorganization',
            name='internal_image_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalImage'),
        ),
        migrations.AddField(
            model_name='newsorganization',
            name='internal_video_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalVideo'),
        ),
        migrations.AddField(
            model_name='newsorganizationnetwork',
            name='internal_audio_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalAudio'),
        ),
        migrations.AddField(
            model_name='newsorganizationnetwork',
            name='internal_document_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalDocument'),
        ),
        migrations.AddField(
            model_name='newsorganizationnetwork',
            name='internal_image_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalImage'),
        ),
        migrations.AddField(
            model_name='newsorganizationnetwork',
            name='internal_video_assets',
            field=models.ManyToManyField(blank=True, to='internalasset.InternalVideo'),
        ),
    ]
