# Generated by Django 3.0.3 on 2020-04-06 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Name of specific discussion.', max_length=250)),
                ('discussion_type', models.CharField(choices=[('ORGANIZATION', 'Organization Discussion'), ('NETWORK', 'Network Discussion'), ('DIRECT', 'Direct Discussion'), ('PROJECT', 'Project Discussion'), ('STORY', 'Story Discussion'), ('ITEM', 'Item Discussion'), ('TASK', 'Task Discussion'), ('EVENT', 'Event Discussion'), ('PITCH', 'Pitch Discussion'), ('ASSIGNMENT', 'Assignment Discussion')], help_text='What kind of discussion it is.', max_length=25)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('anchor', models.OneToOneField(help_text='The anchor object', on_delete=django.db.models.deletion.CASCADE, to='base.Anchor')),
            ],
            options={
                'ordering': ['-creation_date'],
                'unique_together': {('channel', 'anchor')},
            },
        ),
        migrations.CreateModel(
            name='DirectMessageExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(help_text='Participants in this direct message exchange.', related_name='direct_message_exchange_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct Message Exchange',
                'verbose_name_plural': 'Direct Message Exchanges',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the comment.')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Discussion')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
