# Generated by Django 2.2.11 on 2020-04-06 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0004_auto_20200405_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(help_text='Name of specific discussion.', max_length=250)),
                ('discussion_type', models.CharField(choices=[('ORGANIZATION', 'Organization Discussion'), ('NETWORK', 'Network Discussion'), ('DIRECT', 'Direct Discussion'), ('PROJECT', 'Project Discussion'), ('STORY', 'Story Discussion'), ('ITEM', 'Item Discussion'), ('TASK', 'Task Discussion'), ('EVENT', 'Event Discussion'), ('PITCH', 'Pitch Discussion'), ('ASSIGNMENT', 'Assignment Discussion')], help_text='What kind of discussion it is.', max_length=25)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('anchor', models.OneToOneField(help_text='The anchor object', on_delete=django.db.models.deletion.CASCADE, to='base.Anchor')),
            ],
            options={
                'ordering': ['-creation_date'],
                'unique_together': {('channel', 'anchor')},
            },
        ),
    ]
