# Generated by Django 2.2.11 on 2020-04-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='discussion_type',
        ),
    ]
