# Generated by Django 3.0.3 on 2020-04-17 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_remove_discussion_discussion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The content of the message.')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date and time for creation of message.')),
                ('read', models.BooleanField(default=False, help_text='Has the message been seen by all participants.')),
                ('author', models.ForeignKey(help_text='Participant who authored the message.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exchange', models.ForeignKey(help_text='The exchange of participants this message is meant for.', on_delete=django.db.models.deletion.CASCADE, to='communication.DirectMessageExchange')),
            ],
            options={
                'verbose_name': 'Direct Message',
                'verbose_name_plural': 'Direct Messages',
                'ordering': ['-date'],
            },
        ),
    ]
