# Generated by Django 2.2.11 on 2020-04-06 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communication', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessageExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(help_text='Participants in this direct message exchange.', related_name='direct_message_exchange_participant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Direct Message Exchange',
                'verbose_name_plural': 'Direct Message Exchanges',
            },
        ),
    ]
