# Generated by Django 3.0.3 on 2020-12-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0003_directmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='exchange',
            field=models.ForeignKey(help_text='The exchange of participants the message is associated with.', on_delete=django.db.models.deletion.CASCADE, to='communication.DirectMessageExchange'),
        ),
    ]
