# Generated by Django 3.0.3 on 2020-05-02 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='The participants assigned to the task.', related_name='task_team', to=settings.AUTH_USER_MODEL),
        ),
    ]
